#
# The common logrotate config used by each tool account (see README.md).
#
# The log paths are relative to the working directory (i.e. the tool account's home directory) when
# run through `toolforge jobs`.
#

##########
## Set default values for logs below
##########
# keep one week of compressed daily logs, plus today's log
daily
rotate 7
dateext
dateformat -%Y-%m-%d
compress

# don't fail if the log doesn't exist yet
missingok

# don't back up empty log
notifempty

# don't compress the log immediately after rotation
# Lighttpd keeps an open file handle, so it might still be writing to it.
delaycompress

# rotate log with `create` mode
# This renames the log file to the backup, recreates the original path, and then signals Lighttpd to
# reopen it.
#
# We can't just use `copytruncate` instead; Lighttpd keeps an open file handle with O_APPEND mode
# and NFS emulates O_APPEND with a cached file size, so the next write can be at the old offset
# (leading to a long run of NUL characters up to the previous file length).
create
postrotate
    sh $HOME/git/wikimedia-contrib/tool-labs/_scheduledJobs/reopen-lighttpd-logs.sh
endscript


##########
## Enable for each log file
##########
# Lighttpd access log (enabled via ~/.lighttpd.conf)
"./logs/access.log"
{
}

# Toolforge error log
"./error.log"
{
    # `error.log` is in the home folder, but move backups into ~/logs
    # (This is relative to the log file.)
    olddir logs
}

# scheduled job logs (see jobs.yaml)
"./logs/job-*.log"
"./logs/job-*.err"
{
    postrotate
        true
    endscript
}
