#
# The Lighttpd config used by every Toolforge account in this repo. See README.md for usage.
#

##########
## Global rules
##  (must be before conditional blocks)
##########
# enable status pages
server.modules += ("mod_auth", "mod_status")
status.status-url = "/server-status"
status.statistics-url = "/server-statistics"

# enable access log
# %t = end timestamp
# %r = request line (e.g. "GET /url HTTP/1.1")
# %s = HTTP response status code
# %b = HTTP response byte size
# %D = time spent (in microseconds)
# %{Referer}i = the page which linked to this URL, if any
# %{User-Agent}i = the `User-Agent` header provided by the client
accesslog.filename = env.HOME + "/logs/access.log"
accesslog.format = "%t \"%r\" %s %b %D \"%{Referer}i\" \"%{User-Agent}i\""

# disable %2F being treated as a path separator
# By default, Lighttpd decodes '%2F' into '/' *before* the request path is resolved. Since forms are submitted or
# redirected to routes, that can result in submitted values silently getting truncated or split (e.g.
# `/for/212.75.0.1%2F16` being treated as separate '212.75.0.1' and '16' route values).
server.http-parseopts += ("url-path-2f-decode" => "disable")


##########
## tool accounts
##
## These have `public_html/tool` symlinked to their folder, and use a common URL scheme:
##    https://<tool>.toolforge.org/              // the default page (e.g. input form)
##    https://<tool>.toolforge.org/for/<route>   // the lookup result for a given route, if applicable
##########
$HTTP["host"] !~ "^meta[23]?\." {
    # invisibly rewrite pretty URLs into the real query (e.g. /for/a/b => /tool/index.php?@route=a/b)
    url.rewrite-once += (
        "^/for/([^?]*)(?:\?(.*))?$" => "/tool/index.php?$2&@route=$1", # a path starting with `/for/*`; append @route last to override any conflicting query parameter
        "^/(?:for)?(?:\?(.*))?$"    => "/tool/index.php?$1"            # the root path (`/` or `/?*`) or an empty route (`/for` or `/for?*`)
    )
}


##########
## legacy shared accounts (meta, meta2, and meta3)
##   (These don't host tools anymore; they just redirect to the new tool/script accounts, and meta hosts user scripts.)
##########
$HTTP["host"] =~ "^meta[23]?\." {
    url.redirect += (
        # redirect to the account which hosts each tool
        "^/(accounteligibility|catanalysis|crossactivity|globalgroups|gusersearch|magicredirect|stalktoy|stewardry|userpages)(?:/index\.php)?/?(\?.+)?$" => "https://$1.toolforge.org/$2",
        "^/(accounteligibility|catanalysis|crossactivity|globalgroups|gusersearch|magicredirect|stalktoy|stewardry|userpages)/([^\?].*)?$" => "https://$1.toolforge.org/for/$2"
    )


    ##########
    ## redirect each account's root to the tool it used to open on
    ##########
    $HTTP["host"] =~ "^meta\." {
        url.redirect += (
            "^/?$" => "https://accounteligibility.toolforge.org/",

            # redirect user scripts to static server
            "^/scripts/(.*)$" => "https://tools-static.wmflabs.org/meta/scripts/$1"
        )
    }

    $HTTP["host"] =~ "^meta2\." {
        url.redirect += ("^/?$" => "https://crossactivity.toolforge.org/")
    }

    $HTTP["host"] =~ "^meta3\." {
        url.redirect += ("^/?$" => "https://stalktoy.toolforge.org/")
    }
}

