#
# The common logrotate config used by each tool account (see README.md).
#
# The log paths are relative to the working directory (i.e. the tool account's home directory) when
# run through `toolforge jobs`.
#

##########
## Set default values for logs below
##########
# keep one week of compressed daily logs, plus today's log
daily
rotate 7
dateext
dateformat -%Y-%m-%d
compress

# don't fail if the log doesn't exist yet
missingok

# don't back up empty log
notifempty

# truncate original log in-place (to avoid breaking lighttpd's persisted log file handle)
copytruncate


##########
## Enable for each log file
##########
# Lighttpd access log (enabled via ~/.lighttpd.conf)
"./logs/access.log"
{
}

# Toolforge error log
"./error.log"
{
    # keep `error.log` in the home directory, but move backups into ~/logs
    olddir logs
}
